import turtle
turtle.shape("turtle")
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.write(turtle.position())
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
